version: "3.3"

services:

  web:
    build: 
      context: ./docker/php
    volumes:
      - ${APP_PATH_HOST}:/var/www/app
    depends_on: 
      - db
  
  nginx:
    image: nginx:latest
    volumes:
      - ${APP_PATH_HOST}:/var/www/app
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d
    working_dir: /var/www/app
    ports:
      - 80:80
    depends_on:
      - web

  composer:
    image: composer:2.0.11
    volumes:
      - ${APP_PATH_HOST}:/var/www/app
    working_dir: /var/www/app
    command: composer install
    depends_on: 
      - web

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080