version: "3.3"

services:

  web:
    build: 
      context: ./docker/php
    volumes:
      - ./photoApi:/var/www/app
    depends_on: 
      - db
  
  nginx:
    image: nginx:latest
    volumes:
      - ./photoApi:/var/www/app
      - ./docker/nginx/config:/etc/nginx/conf.d
    working_dir: /var/www/app
    ports:
      - 80:80
    depends_on:
      - web

  composer:
    image: composer:2.0.11
    volumes:
      - ./photoApi:/var/www/app
    working_dir: /var/www/app
    command: composer install
    depends_on: 
      - web

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: testapi
      MARIADB_USER: test_user
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080